name: Verify BaseTap Implementation

on:
  workflow_dispatch:
    inputs:
      network:
        type: choice
        description: "Network to verify on"
        options: [sepolia, base, baseSepolia]
        required: true
        default: base
      proxy_address:
        type: string
        description: "Proxy address (ERC1967/Transparent proxy)"
        required: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm and deps
        run: |
          npm i -g pnpm
          pnpm i --no-frozen-lockfile

      - name: Build (compile contracts)
        run: pnpm build

      # Пишем окружение: RPC из repository variables, ключи из secrets
      - name: Write .env from secrets + variables
        run: |
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
          echo "SEPOLIA_RPC_URL=${{ vars.SEPOLIA_RPC_URL }}" >> .env
          echo "BASE_RPC_URL=${{ vars.BASE_RPC_URL }}" >> .env
          echo "BASE_SEPOLIA_RPC_URL=${{ vars.BASE_SEPOLIA_RPC_URL }}" >> .env
          echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> .env
          echo "---- .env ready ----"
          tail -n +1 .env | sed 's/PRIVATE_KEY=.*/PRIVATE_KEY=***masked***/'

      - name: Verify implementation on explorer
        env:
          PROXY_ADDRESS: ${{ github.event.inputs.proxy_address }}
        run: |
          case "${{ github.event.inputs.network }}" in
            sepolia) NET=sepolia ;;
            base) NET=base ;;
            baseSepolia) NET=baseSepolia ;;
          esac
          echo "Verifying implementation behind proxy $PROXY_ADDRESS on $NET ..."
          npx hardhat run --network "$NET" scripts/verify-impl.ts
